import { useMemo, useState } from "react";
import { Loader2, LockKeyhole, Plus, Save, Upload } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { InstitutionalHeader, InstitutionalFooter, NavigationBar } from "@/components/PortalShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

export default function Admin() {
  const { user, loading } = useAuth();
  if (loading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#e30613]" /></div>;
  if (!user) return <AccessGate />;
  if (user.role !== "admin") return <AccessGate message="Seu usuário está autenticado, mas não possui permissão de administrador." />;
  return <AdminContent />;
}

function AdminContent() {
  const utils = trpc.useUtils();
  const { data: areas, isLoading: areasLoading, error: areasError } = trpc.dashboard.areas.useQuery(undefined, { retry: false });
  const { data: projects, isLoading: projectsLoading, error: projectsError } = trpc.dashboard.projects.useQuery(undefined, { retry: false });
  const [selectedProject, setSelectedProject] = useState("");
  const project = useMemo(() => projects?.find(item => String(item.id) === selectedProject), [projects, selectedProject]);
  const createArea = trpc.admin.createArea.useMutation({ onSuccess: () => { toast.success("Área cadastrada."); utils.dashboard.summary.invalidate(); utils.dashboard.areas.invalidate(); }, onError: e => toast.error(e.message) });
  const createProject = trpc.admin.createProject.useMutation({ onSuccess: () => { toast.success("Projeto cadastrado."); utils.dashboard.summary.invalidate(); utils.dashboard.projects.invalidate(); }, onError: e => toast.error(e.message) });
  const updateProject = trpc.admin.updateProject.useMutation({ onSuccess: () => { toast.success("Projeto atualizado."); utils.dashboard.summary.invalidate(); utils.dashboard.projects.invalidate(); utils.dashboard.project.invalidate(); }, onError: e => toast.error(e.message) });
  const createMetric = trpc.admin.createMetric.useMutation({ onSuccess: () => { toast.success("KPI registrado."); utils.dashboard.project.invalidate(); }, onError: e => toast.error(e.message) });
  const createStage = trpc.admin.createStage.useMutation({ onSuccess: () => { toast.success("Etapa adicionada."); utils.dashboard.project.invalidate(); }, onError: e => toast.error(e.message) });
  const createMilestone = trpc.admin.createMilestone.useMutation({ onSuccess: () => { toast.success("Marco adicionado."); utils.dashboard.project.invalidate(); }, onError: e => toast.error(e.message) });
  const uploadPhoto = trpc.admin.uploadPhoto.useMutation({ onSuccess: () => { toast.success("Foto enviada."); utils.dashboard.project.invalidate(); }, onError: e => toast.error(e.message) });
  if (areasLoading || projectsLoading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#e30613]" /></div>;
  if (areasError || projectsError) return <div className="mx-auto max-w-xl py-20 text-center"><h2 className="text-2xl font-black">Não foi possível carregar o back-office</h2><p className="mt-2 text-sm text-neutral-500">Atualize a página ou verifique a conexão com o banco.</p><Button onClick={() => window.location.reload()} className="mt-6 bg-[#e30613] hover:bg-[#c80511]">Tentar novamente</Button></div>;
  return <div className="min-h-screen bg-[#080808] text-white"><InstitutionalHeader section="BACK-OFFICE" /><main className="mx-auto max-w-[1400px] px-5 py-10 md:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#e30613]">Gestão autônoma</p><h1 className="mt-2 text-4xl font-black text-white">Back-office editorial.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Atualize o conteúdo que alimenta o portal executivo sem alterar o código da aplicação.</p></div><Link href="/"><Button variant="outline">Ver portal executivo</Button></Link></div><Tabs defaultValue="cadastro" className="space-y-6"><span id="cadastro" className="sr-only">Cadastro</span><TabsList className="bg-white"><TabsTrigger value="cadastro">Cadastro</TabsTrigger><TabsTrigger value="projeto">Atualizar projeto</TabsTrigger><TabsTrigger value="evidencias">Evidências</TabsTrigger></TabsList><TabsContent value="cadastro" className="grid gap-6 lg:grid-cols-2"><AreaForm onSubmit={input => createArea.mutate(input)} loading={createArea.isPending} /><ProjectForm areas={areas ?? []} onSubmit={input => createProject.mutate(input)} loading={createProject.isPending} /></TabsContent><TabsContent value="projeto"><div className="mb-5 max-w-xl"><Label>Selecione o projeto</Label><Select value={selectedProject} onValueChange={setSelectedProject}><SelectTrigger className="mt-2 bg-white"><SelectValue placeholder="Escolha um projeto" /></SelectTrigger><SelectContent>{projects?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select></div>{project ? <div className="grid gap-6 lg:grid-cols-2"><UpdateForm project={project} onSubmit={data => updateProject.mutate({ id: project.id, data })} loading={updateProject.isPending} /><div className="space-y-6"><MetricForm projectId={project.id} onSubmit={input => createMetric.mutate(input)} loading={createMetric.isPending} /><StageForm projectId={project.id} onSubmit={input => createStage.mutate(input)} loading={createStage.isPending} /><MilestoneForm projectId={project.id} onSubmit={input => createMilestone.mutate(input)} loading={createMilestone.isPending} /></div></div> : <EmptyAdmin text="Selecione um projeto para editar seu status e adicionar informações de acompanhamento." />}</TabsContent><TabsContent value="evidencias"><div className="max-w-2xl">{project ? <PhotoForm projectId={project.id} onSubmit={input => uploadPhoto.mutate(input)} loading={uploadPhoto.isPending} /> : <EmptyAdmin text="Selecione um projeto na aba Atualizar projeto para enviar fotos." />}</div></TabsContent></Tabs><InstitutionalFooter subtitle="Gestão autônoma de conteúdo e evidências." /></main><NavigationBar backHref="/" nextHref="#cadastro" backLabel="Voltar ao portal" /></div>;
}

function AreaForm({ onSubmit, loading }: { onSubmit: (input: { name: string; code: string; description?: string }) => void; loading: boolean }) { const [name, setName] = useState(""); const [code, setCode] = useState(""); const [description, setDescription] = useState(""); return <Card><CardHeader><CardTitle className="flex items-center gap-2 font-black"><Plus className="h-5 w-5 text-[#e30613]" />Nova área</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Nome"><Input value={name} onChange={e => setName(e.target.value)} placeholder="Ex.: Patrimônio Imobiliário" /></Field><Field label="Código"><Input value={code} onChange={e => setCode(e.target.value)} placeholder="Ex.: PAT-IMOB" /></Field><Field label="Descrição"><Textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Descrição curta da área" /></Field><Button disabled={loading || !name || !code} onClick={() => onSubmit({ name, code, description })} className="bg-[#e30613] hover:bg-[#c80511]">Cadastrar área</Button></CardContent></Card>; }
function ProjectForm({ areas, onSubmit, loading }: { areas: { id: number; name: string }[]; onSubmit: (input: { areaId: number; name: string; code: string; summary?: string; owner?: string }) => void; loading: boolean }) { const [areaId, setAreaId] = useState(""); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [summary, setSummary] = useState(""); const [owner, setOwner] = useState(""); return <Card><CardHeader><CardTitle className="flex items-center gap-2 font-black"><Plus className="h-5 w-5 text-[#e30613]" />Novo projeto</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Área"><Select value={areaId} onValueChange={setAreaId}><SelectTrigger><SelectValue placeholder="Escolha a área" /></SelectTrigger><SelectContent>{areas.map(area => <SelectItem key={area.id} value={String(area.id)}>{area.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Nome"><Input value={name} onChange={e => setName(e.target.value)} placeholder="Nome do projeto" /></Field><Field label="Código"><Input value={code} onChange={e => setCode(e.target.value)} placeholder="Ex.: SAM-2026" /></Field><Field label="Resumo"><Textarea value={summary} onChange={e => setSummary(e.target.value)} /></Field><Field label="Responsável"><Input value={owner} onChange={e => setOwner(e.target.value)} /></Field><Button disabled={loading || !areaId || !name || !code} onClick={() => onSubmit({ areaId: Number(areaId), name, code, summary, owner })} className="bg-[#e30613] hover:bg-[#c80511]">Cadastrar projeto</Button></CardContent></Card>; }
function UpdateForm({ project, onSubmit, loading }: { project: any; onSubmit: (data: any) => void; loading: boolean }) { const [name, setName] = useState(project.name); const [summary, setSummary] = useState(project.summary || ""); const [status, setStatus] = useState(project.status); const [progress, setProgress] = useState(String(project.progress)); const [owner, setOwner] = useState(project.owner || ""); const [nextSteps, setNextSteps] = useState(project.nextSteps || ""); return <Card><CardHeader><CardTitle className="flex items-center gap-2 font-black"><Save className="h-5 w-5 text-[#e30613]" />Atualização executiva</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Nome do projeto"><Input value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Resumo executivo"><Textarea value={summary} onChange={e => setSummary(e.target.value)} /></Field><Field label="Status"><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["estruturação", "andamento", "execução", "concluído", "pausado"].map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field><Field label="Progresso (%)"><Input type="number" min="0" max="100" value={progress} onChange={e => setProgress(e.target.value)} /></Field><Field label="Responsável"><Input value={owner} onChange={e => setOwner(e.target.value)} /></Field><Field label="Próximos passos"><Textarea rows={6} value={nextSteps} onChange={e => setNextSteps(e.target.value)} /></Field><Button disabled={loading} onClick={() => onSubmit({ name, summary, status, progress: Number(progress), owner, nextSteps })} className="bg-[#e30613] hover:bg-[#c80511]">Salvar atualização</Button></CardContent></Card>; }
function MetricForm({ projectId, onSubmit, loading }: { projectId: number; onSubmit: (input: any) => void; loading: boolean }) { const [label, setLabel] = useState(""); const [value, setValue] = useState(""); const [target, setTarget] = useState(""); return <Card><CardHeader><CardTitle className="text-lg font-black">Registrar KPI</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><Input placeholder="Indicador" value={label} onChange={e => setLabel(e.target.value)} /><Input type="number" placeholder="Valor" value={value} onChange={e => setValue(e.target.value)} /><Input type="number" placeholder="Meta" value={target} onChange={e => setTarget(e.target.value)} /><Button className="bg-[#171717] sm:col-span-3" disabled={loading || !label || !value} onClick={() => onSubmit({ projectId, label, value: Number(value), target: target ? Number(target) : undefined })}>Adicionar KPI</Button></CardContent></Card>; }
function StageForm({ projectId, onSubmit, loading }: { projectId: number; onSubmit: (input: any) => void; loading: boolean }) { const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); return <Card><CardHeader><CardTitle className="text-lg font-black">Adicionar etapa</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Título da etapa" value={title} onChange={e => setTitle(e.target.value)} /><Textarea placeholder="Descrição" value={description} onChange={e => setDescription(e.target.value)} /><Button className="bg-[#171717]" disabled={loading || !title} onClick={() => onSubmit({ projectId, title, description })}>Adicionar etapa</Button></CardContent></Card>; }
function MilestoneForm({ projectId, onSubmit, loading }: { projectId: number; onSubmit: (input: any) => void; loading: boolean }) { const [title, setTitle] = useState(""); const [date, setDate] = useState(""); return <Card><CardHeader><CardTitle className="text-lg font-black">Adicionar marco</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Título do marco" value={title} onChange={e => setTitle(e.target.value)} /><Input type="date" value={date} onChange={e => setDate(e.target.value)} /><Button className="bg-[#171717]" disabled={loading || !title || !date} onClick={() => onSubmit({ projectId, title, milestoneDate: new Date(`${date}T12:00:00`) })}>Adicionar marco</Button></CardContent></Card>; }
function PhotoForm({ projectId, onSubmit, loading }: { projectId: number; onSubmit: (input: any) => void; loading: boolean }) { const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const send = () => { if (!file) return; const reader = new FileReader(); reader.onload = () => onSubmit({ projectId, fileName: file.name, mimeType: file.type, data: String(reader.result), title, description }); reader.readAsDataURL(file); }; return <Card><CardHeader><CardTitle className="flex items-center gap-2 font-black"><Upload className="h-5 w-5 text-[#e30613]" />Enviar evidência fotográfica</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Arquivo de imagem"><Input type="file" accept="image/*" onChange={e => setFile(e.target.files?.[0] || null)} /></Field><Field label="Título"><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="Ex.: Inventário físico" /></Field><Field label="Descrição"><Textarea value={description} onChange={e => setDescription(e.target.value)} /></Field><Button disabled={loading || !file} onClick={send} className="bg-[#e30613] hover:bg-[#c80511]">Enviar foto</Button></CardContent></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function EmptyAdmin({ text }: { text: string }) { return <Card className="border-dashed"><CardContent className="py-16 text-center text-sm text-neutral-500">{text}</CardContent></Card>; }
function AccessGate({ message = "A área de gestão exige autenticação de administrador." }: { message?: string }) { return <div className="min-h-screen bg-[#171717] text-white"><InstitutionalHeader section="BACK-OFFICE" /><div className="mx-auto flex max-w-md flex-col items-center px-6 py-28 text-center"><LockKeyhole className="h-12 w-12 text-[#e30613]" /><h1 className="mt-6 text-3xl font-black">Acesso restrito</h1><p className="mt-3 text-sm leading-6 text-white/60">{message}</p><Button onClick={() => startLogin()} className="mt-8 bg-[#e30613] hover:bg-[#c80511]">Entrar como administrador</Button></div></div>; }
