import { ArrowUpRight, BarChart3, FolderKanban, Gauge, Images, Loader2, Plus, Settings2 } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { InstitutionalHeader, InstitutionalFooter, AdminLink, NavigationBar } from "@/components/PortalShell";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type PortfolioFilter = "all" | "active" | "completed";

export default function Home() {
  const { data, isLoading, error } = trpc.dashboard.summary.useQuery();
  const [portfolioFilter, setPortfolioFilter] = useState<PortfolioFilter>("all");

  if (isLoading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#e30613]" /></div>;
  if (error) return <div className="p-10 text-center"><p className="font-semibold">Não foi possível carregar o painel.</p><p className="mt-2 text-sm text-neutral-500">Verifique a conexão com o banco e tente novamente.</p></div>;

  const totals = data?.totals ?? { projects: 0, active: 0, completed: 0, averageProgress: 0 };
  const projects = data?.projects ?? [];
  const sortedProjects = [...projects].sort((a, b) => a.code.localeCompare(b.code, undefined, { numeric: true }));
  const filteredProjects = portfolioFilter === "completed" ? sortedProjects.filter(project => project.status === "concluído") : portfolioFilter === "active" ? sortedProjects.filter(project => project.status !== "concluído") : sortedProjects;

  return <div className="min-h-screen bg-[#080808] text-white institutional-pattern">
    <section className="relative overflow-hidden bg-[#171717] text-white">
      <div className="hero-overlay absolute inset-0" />
      <div className="relative z-10"><InstitutionalHeader section="SU​​COR · SUBSECRETARIA DE GESTÃO CORPORATIVA" /><div className="grid min-h-[330px] items-center gap-10 px-6 py-12 md:grid-cols-[1.2fr_.8fr] md:px-16"><div><div className="mb-7 h-2 w-24 bg-[#e30613]" /><p className="mb-3 text-xs font-bold uppercase tracking-[.28em] text-[#e30613]">Portal executivo</p><h1 className="max-w-3xl text-4xl font-black uppercase leading-[.98] tracking-tight md:text-6xl">Divisão de Patrimônio (DPAT)</h1><p className="mt-4 text-lg font-bold uppercase tracking-[.12em] text-white/85">Portal de acompanhamento de Projetos</p><p className="mt-5 max-w-xl text-sm leading-6 text-white/70 md:text-base">Visão consolidada da evolução, movimentações, entregas e próximos passos das áreas responsáveis.</p></div><div className="hidden justify-self-end border-l border-white/20 pl-8 md:block"><p className="text-xs uppercase tracking-[.24em] text-white/50">Atualização em tempo real</p><p className="mt-3 text-5xl font-black text-[#e30613]">{totals.averageProgress}%</p><p className="text-sm text-white/70">progresso médio dos projetos</p></div></div></div>
    </section>
    <main className="mx-auto max-w-[1500px] px-5 py-10 md:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#e30613]">Visão macro</p><h2 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">Painel consolidado.</h2></div><AdminLink /></div>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricFilterButton active={portfolioFilter === "all"} onClick={() => setPortfolioFilter("all")} icon={<FolderKanban />} label="Projetos cadastrados" value={totals.projects} /><MetricFilterButton active={portfolioFilter === "active"} onClick={() => setPortfolioFilter("active")} icon={<Gauge />} label="Projetos em andamento" value={totals.active} /><MetricFilterButton active={portfolioFilter === "completed"} onClick={() => setPortfolioFilter("completed")} icon={<BarChart3 />} label="Projetos concluídos" value={totals.completed} /><MetricCard icon={<Images />} label="Áreas monitoradas" value={data?.areas.length ?? 0} /></section>
      <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e30613]">Nível 1</p><h3 className="mt-1 text-2xl font-black">Áreas e departamentos</h3></div><span className="text-xs text-neutral-500">Selecione uma área para abrir o dashboard.</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data?.areas.length ? data.areas.map((area, index) => <Link key={area.id} href={`/area/${area.id}`}><Card className="group h-full cursor-pointer border-black/10 bg-white transition-all hover:-translate-y-1 hover:border-[#e30613]/50 hover:shadow-xl"><CardContent className="p-6"><div className="flex items-start justify-between"><span className="text-3xl font-black text-neutral-200">{String(index + 1).padStart(2, "0")}</span><ArrowUpRight className="h-5 w-5 text-neutral-300 transition group-hover:text-[#e30613]" /></div><h4 className="mt-10 text-lg font-black uppercase">{area.name}</h4><p className="mt-3 line-clamp-3 text-sm leading-6 text-neutral-500">{area.description || "Área responsável pelo acompanhamento e execução de projetos estratégicos."}</p></CardContent></Card></Link>) : <EmptyState title="Nenhuma área cadastrada" text="Acesse o back-office para cadastrar o primeiro departamento e iniciar o acompanhamento." />}</div></section>
      <section id="carteira" className="mt-12"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e30613]">Carteira atual</p><h3 className="mt-1 text-2xl font-black">{portfolioFilter === "all" ? "Todos os projetos" : portfolioFilter === "active" ? "Projetos em andamento" : "Projetos concluídos"}</h3></div><Link href="/admin"><Button variant="outline" className="hidden border-black/20 sm:flex"><Plus className="mr-2 h-4 w-4" />Gerenciar conteúdo</Button></Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filteredProjects.length ? filteredProjects.map(project => <Link key={project.id} href={`/projeto/${project.id}`}><Card className="h-full border-black/10 bg-white transition hover:border-[#e30613]/40 hover:shadow-lg"><CardContent className="p-5"><p className="text-xs font-bold tracking-widest text-neutral-400">{project.code}</p><h4 className="mt-4 text-lg font-black uppercase">{project.name}</h4><p className="mt-3 text-sm font-bold text-neutral-700">Responsável: {project.owner || "A definir"}</p><p className="mt-2 line-clamp-3 text-sm leading-6 text-neutral-500">{project.summary || "Resumo do tema ainda não cadastrado."}</p></CardContent></Card></Link>) : <EmptyState title="Nenhum projeto encontrado" text="Não há projetos correspondentes ao filtro selecionado." />}</div></section>
      <InstitutionalFooter />
    </main><NavigationBar nextHref="#carteira" backLabel="Ir para a carteira" />
  </div>;
}

function MetricFilterButton({ icon, label, value, active, onClick }: { icon: React.ReactNode; label: string; value: number; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className="text-left"><MetricCard icon={icon} label={label} value={value} active={active} /></button>; }
function MetricCard({ icon, label, value, active = false }: { icon: React.ReactNode; label: string; value: number; active?: boolean }) { return <Card className={`border-black/10 bg-white transition ${active ? "ring-2 ring-[#e30613] ring-offset-2" : "hover:border-[#e30613]/50"}`}><CardContent className="flex items-center gap-4 p-5"><span className="flex h-11 w-11 items-center justify-center bg-[#fff0f1] text-[#e30613]">{icon}</span><div><p className="text-3xl font-black">{value}</p><p className="text-xs uppercase tracking-wider text-neutral-500">{label}</p></div></CardContent></Card>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <Card className="border-dashed border-black/20 bg-white md:col-span-2 xl:col-span-4"><CardContent className="flex flex-col items-center justify-center px-6 py-14 text-center"><Settings2 className="h-8 w-8 text-[#e30613]" /><h4 className="mt-4 font-black">{title}</h4><p className="mt-2 max-w-md text-sm text-neutral-500">{text}</p><Link href="/admin" className="mt-5"><Button className="bg-[#e30613] hover:bg-[#c80511]">Abrir back-office</Button></Link></CardContent></Card>; }
