from pathlib import Path
import re

path = Path('/home/ubuntu/portal-acompanhamento-projetos/client/src/pages/Admin.tsx')
text = path.read_text()
start = text.index('function UserManagement(')
end = text.index('function StageForm(', start)
replacement = r'''function UserManagement({ users, areas, actorProfile, auditLogs, onCreate, onUpdate, loading }: { users: any[]; areas: AdminArea[]; actorProfile: UserProfile; auditLogs: any[]; onCreate: (input: { openId: string; name: string; email: string; profile: UserProfile; areaIds: number[] }) => void; onUpdate: (id: number, data: { profile?: UserProfile; areaIds?: number[]; isActive?: boolean }) => void; loading: boolean }) {
  const [openId, setOpenId] = useState("");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [profile, setProfile] = useState<UserProfile>("consulta");
  const [areaIds, setAreaIds] = useState<number[]>([]);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editingProfile, setEditingProfile] = useState<UserProfile>("consulta");
  const [editingAreaIds, setEditingAreaIds] = useState<number[]>([]);
  const toggleArea = (setter: (updater: (current: number[]) => number[]) => void, id: number) => setter(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const profileOptions = assignableProfiles(actorProfile).map(value => ({ value, label: USER_PROFILE_LABELS[value], description: USER_PROFILE_DESCRIPTIONS[value] }));
  const permissionMatrix = [
    { profile: "admin_geral" as UserProfile, access: "Acesso completo", canCreate: "Pode criar qualquer perfil", scope: "Todos os setores" },
    { profile: "gestor_setor" as UserProfile, access: "Gestão operacional setorial", canCreate: "Editor de Projetos e Consulta", scope: "Somente setores vinculados" },
    { profile: "editor_projetos" as UserProfile, access: "Edição de projetos", canCreate: "Consulta", scope: "Projetos autorizados" },
    { profile: "consulta" as UserProfile, access: "Somente leitura", canCreate: "Não cria perfis", scope: "Conteúdo permitido" },
  ];
  const firstAssignableProfile = profileOptions[0]?.value ?? "consulta";
  return <div className="space-y-6">
    <Card className="border-[#e30613]/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg font-black"><ShieldCheck className="h-5 w-5 text-[#e30613]" />Matriz de permissões</CardTitle><p className="text-sm text-neutral-500">As opções de atribuição abaixo respeitam o seu perfil atual: <strong>{USER_PROFILE_LABELS[actorProfile]}</strong>.</p></CardHeader><CardContent><div className="overflow-x-auto rounded-md border border-neutral-200"><table className="min-w-full text-left text-xs"><thead className="bg-neutral-100 uppercase tracking-wide text-neutral-600"><tr><th className="px-3 py-3">Perfil</th><th className="px-3 py-3">Acesso</th><th className="px-3 py-3">Pode criar</th><th className="px-3 py-3">Abrangência</th></tr></thead><tbody>{permissionMatrix.map(item => <tr key={item.profile} className="border-t border-neutral-100"><td className="px-3 py-3 font-bold">{USER_PROFILE_LABELS[item.profile]}</td><td className="px-3 py-3">{item.access}</td><td className="px-3 py-3">{item.canCreate}</td><td className="px-3 py-3">{item.scope}</td></tr>)}</tbody></table></div></CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]">
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg font-black"><UserPlus className="h-5 w-5 text-[#e30613]" />Adicionar usuário</CardTitle></CardHeader><CardContent className="space-y-4">
        <Field label="Open ID"><Input value={openId} onChange={e => setOpenId(e.target.value)} placeholder="Identificador OAuth" /></Field>
        <Field label="Nome"><Input value={name} onChange={e => setName(e.target.value)} /></Field>
        <Field label="E-mail"><Input type="email" value={email} onChange={e => setEmail(e.target.value)} /></Field>
        <Field label="Perfil"><Select value={profile} onValueChange={value => setProfile(value as UserProfile)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{profileOptions.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select><p className="mt-1 text-xs text-neutral-500">{USER_PROFILE_DESCRIPTIONS[profile]}</p></Field>
        {profile === "gestor_setor" && <Field label="Setores vinculados"><div className="grid gap-2 rounded-md border border-neutral-200 bg-neutral-50 p-3">{areas.map(area => <label key={area.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={areaIds.includes(area.id)} onChange={() => toggleArea(setAreaIds, area.id)} />{area.shortCode ? `${area.shortCode} — ` : ""}{area.name}</label>)}</div></Field>}
        <Button disabled={loading || !openId || !name || !email || !profileOptions.length} onClick={() => onCreate({ openId, name, email, profile, areaIds })} className="bg-[#e30613] hover:bg-[#c80511]">Cadastrar usuário</Button>
      </CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg font-black"><ShieldCheck className="h-5 w-5 text-[#e30613]" />Usuários cadastrados</CardTitle><p className="text-sm text-neutral-500">Gestores de Setor visualizam somente usuários com vínculo em seus setores.</p></CardHeader><CardContent className="space-y-3">{users.length ? users.map(user => { const currentProfile = (user.profile || (user.role === "admin" ? "admin_geral" : "consulta")) as UserProfile; const isEditing = editingId === user.id; return <div key={user.id} className="rounded-md border border-neutral-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{user.name || "Sem nome"}</p><p className="text-xs text-neutral-500">{user.email} · {USER_PROFILE_LABELS[currentProfile]}</p>{user.areaIds?.length ? <p className="mt-1 text-xs text-neutral-500">Setores: {user.areaIds.map((id: number) => areas.find(area => area.id === id)?.shortCode || `#${id}`).join(", ")}</p> : null}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => { setEditingId(isEditing ? null : user.id); setEditingProfile(currentProfile); setEditingAreaIds(user.areaIds || []); }} disabled={loading}>{isEditing ? "Cancelar" : "Editar perfil"}</Button><Button size="sm" variant={user.isActive === false ? "default" : "outline"} onClick={() => onUpdate(user.id, { isActive: user.isActive === false })} disabled={loading}>{user.isActive === false ? "Ativar" : "Desativar"}</Button></div></div>{isEditing && <div className="mt-4 space-y-3 border-t border-neutral-100 pt-4"><Field label="Perfil"><Select value={editingProfile} onValueChange={value => setEditingProfile(value as UserProfile)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{profileOptions.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></Field>{editingProfile === "gestor_setor" && <Field label="Setores vinculados"><div className="grid gap-2 rounded-md border border-neutral-200 bg-neutral-50 p-3">{areas.map(area => <label key={area.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editingAreaIds.includes(area.id)} onChange={() => toggleArea(setEditingAreaIds, area.id)} />{area.shortCode ? `${area.shortCode} — ` : ""}{area.name}</label>)}</div></Field>}<Button size="sm" className="bg-[#171717]" disabled={loading} onClick={() => { onUpdate(user.id, { profile: editingProfile, areaIds: editingAreaIds }); setEditingId(null); }}>Salvar perfil</Button></div>}</div>; }) : <p className="text-sm text-neutral-500">Nenhum usuário encontrado nos setores permitidos.</p>}</CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg font-black"><ScrollText className="h-5 w-5 text-[#e30613]" />Auditoria de perfis</CardTitle><p className="text-sm text-neutral-500">Registro de criações e alterações de perfil, setores e status.</p></CardHeader><CardContent><div className="max-h-[420px] space-y-3 overflow-auto">{auditLogs.length ? auditLogs.map(log => <div key={log.id} className="border-b border-neutral-100 pb-3 text-xs last:border-0"><p className="font-bold">{log.action === "create" ? "Perfil criado" : "Perfil alterado"}: {USER_PROFILE_LABELS[log.newProfile as UserProfile] || log.newProfile}</p><p className="mt-1 text-neutral-500">Alvo: {log.target?.name || log.target?.email || `Usuário #${log.targetUserId}`} · por {log.actor?.name || log.actor?.email || `Usuário #${log.actorUserId}`}</p><p className="mt-1 text-neutral-500">{new Date(log.createdAt).toLocaleString()}</p></div>) : <p className="text-sm text-neutral-500">Nenhuma alteração de perfil registrada.</p>}</div></CardContent></Card>
  </div>;
}
'''
path.write_text(text[:start] + replacement + text[end:])
